monitor=,preferred,auto,1

$mainMod = SUPER

bind = $mainMod, Return, exec, kitty
bind = $mainMod, Q, killactive,
bind = $mainMod, F, fullscreen,
bind = $mainMod, R, exec, rofi -show drun
bind = $mainMod, E, exit,

exec-once = waybar
